### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by annamalai-saro** [annamalai-saro/PageMetrics#1]
- [ ] Add more metrics
- [ ] Send data by beacon API
- [ ] Async load library
- [ ] Make it standalone library
